version: '3'
services:
  cvote-frontend:
    container_name: cvote-frontend
    image: nginx:alpine
    ports:
      - 80:80
#    build: .

    volumes:
      - ./nginx/proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist
