version : "3"
services:
  cvote-mongo:
    image: mongo:3.7
    container_name: cvote-mongo
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017

  cvote-backend:
    environment:
      - NODE_ENV=production
    container_name: cvote-backend
    image: cvote-backend
    build: .
    command: npm run start:production
    volumes:
      - ./index.ts:/app/index.ts
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./env:/app/env
    ports:
      - 3000:3000
    links:
      - cvote-mongo

